#
# Table templates
#

CREATE TABLE topic (
	id SERIAL PRIMARY KEY,
	name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE payload (
	id SERIAL PRIMARY KEY,
	ts TIMESTAMP DEFAULT NOW(),
	topic_id INTEGER NOT NULL,
	value NUMERIC(24, 3) NULL,
	payload VARCHAR NULL
);

